theme: jekyll-theme-minimal
title: Kisu Bot - Discord Card Collection Assistant
description: Enhance your card collection experience with Nairi bot. Get notified when your favorite series spawn and easily manage your card collections!
